### ISSUE TITLE
Issue deploying cloudformation

### ISSUE THREAD

**Issue by mharnicher-cxp** [LeoPlatform/Leo#4]
The following are the errors I get trying to deploy the stack:

![Screen Shot 2021-02-03 at 6 00 34 PM](https://user-images.githubusercontent.com/8713659/106829640-c47b6900-6649-11eb-96fe-70276f82c24d.png)

**Comment by zirkerc** [comment]
Hi Max, What link are you using for the cloud formation? Are you doing the
update via aws console?

Clint

**Comment by mharnicher-cxp** [comment]
Ah thank you for the prompt response, the following is the link i am using:
`https://s3.amazonaws.com/leo-cli-publishbucket-abb4i613j9y9/leo/1.0.0/cloudformation-1559303801295.json`

And yes, I was trying create the stack from the console.

**Comment by zirkerc** [comment]
I found the cause of the issue.

The Stack template for Leo 1.0.0 is referencing latest for the Bus.  A
newer version of the bus was released which has new input parameters, the
Leo 1.0.0 template isn't providing the parameters because they didn't exist
at the time.

We will need to add those Bus parameters to the Leo template and pass them
through.

**Comment by mharnicher-cxp** [comment]
glad you found the cause! let me know if you need anything else from me.

**Comment by zirkerc** [comment]
I've created an updated cloudformation template.   
https://leo-cli-publishbucket-mzhr7agmqo7u.s3-us-west-2.amazonaws.com/leo/1.0.1/cloudformation-1612897964657.json

It adds a few stack parameters but defaults for those parameters work just fine

**Comment by mharnicher-cxp** [comment]
Great thank you, i'll give that one a go!

**Comment by mharnicher-cxp** [comment]
that one seems to work for me!
